### ISSUE TITLE
Cannot run bamboo.estimate in the BiocParallel::bplapply for multiple sequences

### ISSUE THREAD

**Issue by zhanghao-njmu** [dbdahl/bamboo#1]
I want to predict the secondary structure for many sequences using multi-threads. When I run bamboo.estimate in the BiocParallel::bplapply(), I encountered the following error :
```
Error: BiocParallel errors
  element index: 1, 2, 3, 4, 5, 6, ...
  first error: Each process should have its own Scala bridge.  Closing this bridge.
```
I found bamboo used the scala bridge and one Scala bridge cannot be shared across multiple R processes/threads according to the rscala manual. 
How to fix this error or is there any other approach to predict multiple sequences?

**Comment by dbdahl** [comment]
Yes, unfortunately, it is not easy to use bamboo for sequences in parallel from a single R instance.  The easiest solution is to run multiple R instances, each of which predicts one secondary structure at a time.  Sorry.
